[package]
name = "mdbook-frontmatter-strip"
version = "0.1.0"
edition = "2021"

[dependencies]
mdbook = "0.4.40"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
anyhow = "1"
clap = {version = "4", features = ["derive"]}
semver = "1"
